---
title: "Tricks"
author: "Sergio Uribe"
date: "6 de marzo de 2018"
output: html_document
---
# Search & Replace tidyverse way

```{r, message=FALSE}
library(tidyverse)
```

```{r}
df <- data.frame(
  c1 = letters[1:5], 
  c2 = 5:9, 
  c3 = LETTERS[5:9], 
  stringsAsFactors = FALSE)
```

```{r}
df
```

```{r}
df %>% 
  mutate_if(is.character, str_replace_all, pattern = '[aeouAEOU]', replacement = 'ths should be aeouAEIOU except i or I ')

```


# Find NAs

```{r, eval=FALSE}
`new_DF <- df[is.na(df$columna),]`
```

# Create fake data from a table

Create table
```{r, eval=FALSE}
originalTable <- matrix(c(188, 29, 20, 51), ncol = 2, byrow = TRUE)
colnames(originalTable) <- c("A", "B")
rownames(originalTable) <- c("C", "D")
originalTable
```
Package splitstackshape
```{r, eval=FALSE}
library(splitstackshape)
df <- expandRows(data.frame(as.table(originalTable)), "Freq")
table(df$Var1, df$Var2)
```

# Sum rows
```{r, eval=FALSE}
 mutate(newVar = rowSums( cbind (colA,colB), na.rm=TRUE))
```

# Clean data from rectangular dataframes
```{r, eval=FALSE}
x = data.frame(a = c(1, NA, 2), b = c(2, NA, 3), c = c(NA, "A", NA))
```

```{r, eval=FALSE}
as.data.frame(lapply(x, na.omit))
```

# Re-ordering columns
```{r, eval=FALSE}
mtcars %>% 
    select(cyl, disp, hp, everything()) %>% 
    head()
```



