---
title: Dentists in OCDE countries
author: Sergio Uribe
date: '2018-02-26'
slug: dentists-in-ocde-countries
draft: true
categories: []
tags:
  - Countries


---

# Packages

```{r, eval=FALSE}
library(tidyverse)
```


# With CSV files

## DMFT at age 12
  
```{r}
DMFT <- read_csv("./datasets/HEALTH_STAT_27022018070930382.csv")
```

```{r}
DMFT <- DMFT %>% 
        select(Country, Year, Value)
```


```{r}
DMFT %>% 
        filter(Year > 1979) %>% 
        ggplot(aes(x = Year, y = Value)) +
        geom_line()  + 
        facet_wrap(~Country) + 
        labs(
                title = "Average decayed, missing, filled teeth (DMFT) at age 12.", 
                subtitle = "OECD Countries. Made with ggplot2. SUE",
                y = "DMFT average", 
                x = "Year"
        ) + 
        theme_minimal()
```

## Dentists

```{r}
dentists <-  read_csv("./datasets/HEALTH_REAC_27022018211859180.csv")
```

```{r}
dentists <- dentists %>% 
        select(VAR, Country, Year, Value)
```

```{r}
dentists %>% 
        filter(Country == "Chile")
```

```{r}
table(dentists$VAR)
```
DNSTDENT: 
DNSTLPDN 
DNSTPADN 

```{r}
dentists %>% 
        filter(Year > 1990) %>% 
        ggplot(aes(x = Year, y = Value,  color = Country)) + 
        geom_line() + 
        scale_y_log10()
```



```{r, eval=FALSE}
library(OECD)
```

```{r}
search_dataset("HEALTH",  # term to search
               data = get_datasets(),  # in all datasets
               ignore.case = TRUE)
```
I'm interested in the HEALTH_STAT, and since I know the name of the exact dataset (HEALTH_STAT_9)

```{r}
dataset <- "HEALTH_STAT"
dstruc <- get_data_structure(dataset)
str(dstruc, max.level = 1)

```

```{r}
dstruc$VAR
```


Here, two ??????? are related to oral health: 
  - DENTDMTF	Decayed-missing-filled teeth (DMFT)
  - DENT	Dental health


```{r}
library(rsdmx)
```

Dentists
http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/HEALTH_REAC/DNSTDENT+DNSTPADN+DNSTLPDN.PERSMYNB+DENSPPNB.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+NMEC+BRA+CHN+COL+CRI+IND+IDN+LTU+RUS+ZAF/all?startTime=1980&endTime=2016



DMFT at age 12
http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/HEALTH_STAT/DENTDMTF.EVIDUREV+EVIFHOEV+EVIHFEEV+NBFEMEPF+NBMALEPH+NBPOPUPC+TXCRUDTF+TXCRUDTH+TXCRUDTX+TXCMFETF+TXCMHOTH+TXCMILTX+RATEPTTX+TXMILBTH+TXCMMMTX+ANNFEMTF+ANNHOMTH+ANNTOTTX+PERCALEF+LIVBRTTX+DENPERNB+NEWCASTX+PERCMTTX+NBWOMAPF+NBMANYPH+NBPOPIPC+INCITFTF+INCITHTH+BLESSETX+JOUPANNB+NOMBRENB.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+NMEC+BRA+CHN+COL+CRI+IND+IDN+LTU+RUS+ZAF/all?startTime=2000&endTime=2016


```{r}

DMFT_12 <- readSDMX(file = "http://stats.oecd.org/restsdmx/sdmx.ashx/GetData/HEALTH_STAT/DENTDMTF.EVIDUREV+EVIFHOEV+EVIHFEEV+NBFEMEPF+NBMALEPH+NBPOPUPC+TXCRUDTF+TXCRUDTH+TXCRUDTX+TXCMFETF+TXCMHOTH+TXCMILTX+RATEPTTX+TXMILBTH+TXCMMMTX+ANNFEMTF+ANNHOMTH+ANNTOTTX+PERCALEF+LIVBRTTX+DENPERNB+NEWCASTX+PERCMTTX+NBWOMAPF+NBMANYPH+NBPOPIPC+INCITFTF+INCITHTH+BLESSETX+JOUPANNB+NOMBRENB.AUS+AUT+BEL+CAN+CHL+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+NMEC+BRA+CHN+COL+CRI+IND+IDN+LTU+RUS+ZAF/all?startTime=2000&endTime=2016")
```


# Library OECD
```{r}
library(OECD)
```

```{r}
dataset_list <- get_datasets()
search_dataset("HEALTH", data = dataset_list)
```

```{r}
dataset <- "HEALTH_STAT"
```

```{r}
dstruc <- get_data_structure("HEALTH_STAT")
str(dstruc, max.level = 1)

```

